In [ ]:
!pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.3.2.tar.gz (281.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.4/281.4 MB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 KB 23.7 MB/s eta 0:00:00
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.3.2-py2.py3-none-any.whl size=281824025 sha256=3a05e8cb6e0b7b320ab4f4b3fdf730d28bba11612c8bac1f5d50436403d91ad6
  Stored in directory: /root/.cache/pip/wheels/6c/e3/9b/0525ce8a69478916513509d43693511463c6468db0de237c86
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.2

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
%cd drive/MyDrive/colabNotebooks

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/colabNotebooks

In [ ]:
!ls

advertising.csv  Advertising.xls  industry.csv

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
spark = SparkSession \
.builder \
.appName("Python Spark SQL basic example") \
.config("spark.some.config.option", "some-value") \
.getOrCreate()

There are two main ways to create the RDDs: loading an external dataset, or distributing aset of collection of objects.

In [ ]:
df = spark.sparkContext.parallelize([(1, 2, 3, 'a b c'),
(4, 5, 6, 'd e f'),
(7, 8, 9, 'g h i')]).toDF(['col1', 'col2', 'col3','col4'])

here we are creating RDDs by using
parallelize() fucntion which takes an already existing collection in your program and pass the same
to the Spark Context.

In [ ]:
df.show()

+----+----+----+-----+
|col1|col2|col3| col4|
+----+----+----+-----+
|   1|   2|   3|a b c|
|   4|   5|   6|d e f|
|   7|   8|   9|g h i|
+----+----+----+-----+

By using createDataFrame( ) function

In [ ]:
Employee = spark.createDataFrame([
('1', 'Joe', '70000', '1'),
('2', 'Henry', '80000', '2'),
('3', 'Sam', '60000', '2'),
('4', 'Max', '90000', '1')],
['Id', 'Name', 'Sallary','DepartmentId']
)

In [ ]:
Employee.show()

+---+-----+-------+------------+
| Id| Name|Sallary|DepartmentId|
+---+-----+-------+------------+
|  1|  Joe|  70000|           1|
|  2|Henry|  80000|           2|
|  3|  Sam|  60000|           2|
|  4|  Max|  90000|           1|
+---+-----+-------+------------+

3. By using read and load function

In [ ]:
!ls

advertising.csv  Advertising.xls  industry.csv

In [ ]:
csv_df=spark.read.format("csv").option("header","true").load('industry.csv')

In [ ]:
csv_df.show()

+--------------------+
|            Industry|
+--------------------+
|  Accounting/Finance|
|Advertising/Publi...|
|  Aerospace/Aviation|
|Arts/Entertainmen...|
|          Automotive|
|    Banking/Mortgage|
|Business Development|
|Business Opportunity|
|Clerical/Administ...|
|Construction/Faci...|
|      Consumer Goods|
|    Customer Service|
|  Education/Training|
|    Energy/Utilities|
|         Engineering|
| Government/Military|
|               Green|
|          Healthcare|
|  Hospitality/Travel|
|     Human Resources|
+--------------------+
only showing top 20 rows

In [ ]:
ds = spark.read.format('com.databricks.spark.csv').\
options(header='true', \
inferschema='true').\
load("industry.csv",
header=True)

df.show(5)
df.printSchema()

+----+----+----+-----+
|col1|col2|col3| col4|
+----+----+----+-----+
|   1|   2|   3|a b c|
|   4|   5|   6|d e f|
|   7|   8|   9|g h i|
+----+----+----+-----+

root
 |-- col1: long (nullable = true)
 |-- col2: long (nullable = true)
 |-- col3: long (nullable = true)
 |-- col4: string (nullable = true)

In [ ]:
! pip install pandas
import pandas as pd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

**Rdd DF vs Pandas DF**

In [ ]:
my_list = [['a', 1, 2], ['b', 2, 3],['c', 3, 4]]
col_name = ['A', 'B', 'C']

In [ ]:
pd_df = pd.DataFrame(my_list, columns= col_name)

In [ ]:
sp_df = spark.createDataFrame(my_list, col_name).show()

+---+---+---+
|  A|  B|  C|
+---+---+---+
|  a|  1|  2|
|  b|  2|  3|
|  c|  3|  4|
+---+---+---+

In [ ]:
# df = spark.read \
#   .format("com.microsoft.sqlserver.jdbc.spark") \
#   .option("url", "jdbc:sqlserver://{SERVER_ADDR};databaseName=emp;") \
#   .option("dbtable", "employee") \
#   .option("user", "replace_user_name") \
#   .option("password", "replace_password") \
#   .load()

# df.show()

### Show First n columns

In [ ]:
# Pandas
pd_df.head(3)

   A  B  C
0  a  1  2
1  b  2  3
2  c  3  4

In [ ]:
ds.show(4)

+--------------------+
|            Industry|
+--------------------+
|  Accounting/Finance|
|Advertising/Publi...|
|  Aerospace/Aviation|
|Arts/Entertainmen...|
+--------------------+
only showing top 4 rows

###Check object datatype

In [ ]:
pd_df.dtypes

A    object
B     int64
C     int64
dtype: object

In [ ]:
ds.dtypes

[('Industry', 'string')]

### Fill Nulls

In [ ]:
my_list = [['male', 1, None], ['female', 2, 3],['male', 3, 4]]

In [ ]:
dp = pd.DataFrame(my_list, columns = ['a','b','c'])
dp

        a  b    c
0    male  1  NaN
1  female  2  3.0
2    male  3  4.0

In [ ]:
ds = spark.createDataFrame(my_list, ['a','b','c'])
ds.show()

+------+---+----+
|     a|  b|   c|
+------+---+----+
|  male|  1|null|
|female|  2|   3|
|  male|  3|   4|
+------+---+----+

In [ ]:
dp.fillna(-99)
#

        a  b     c
0    male  1 -99.0
1  female  2   3.0
2    male  3   4.0



---

In [ ]:
ds.fillna(-99).show()

+------+---+---+
|     a|  b|  c|
+------+---+---+
|  male|  1|-99|
|female|  2|  3|
|  male|  3|  4|
+------+---+---+

### Replace Values
-Pandas you can replace a value with a different datattype
_spark you can only replace a value with a value of same datattype

In [ ]:
dp.a.replace(['male', 'female'], [1,0], inplace=True)
dp

   a  b    c
0  1  1  NaN
1  0  2  3.0
2  1  3  4.0

In [ ]:
ds.na.replace(['male', 'female'], ['1','0']).show()

+---+---+----+
|  a|  b|   c|
+---+---+----+
|  1|  1|null|
|  0|  2|   3|
|  1|  3|   4|
+---+---+----+

### Rename columns

In [ ]:
dp.columns = ['a','b','c']

In [ ]:
ds.toDF('a','b','c').show()
ds.show()

+------+---+----+
|     a|  b|   c|
+------+---+----+
|  male|  1|null|
|female|  2|   3|
|  male|  3|   4|
+------+---+----+

+------+---+----+
|     a|  b|   c|
+------+---+----+
|  male|  1|null|
|female|  2|   3|
|  male|  3|   4|
+------+---+----+

In [ ]:
mapping = {'a':'gender', 'b':'number'}
dp.rename(columns=mapping)

   gender  number    c
0       1       1  NaN
1       0       2  3.0
2       1       3  4.0

In [ ]:
new_names = [mapping.get(col,col) for col in ds.columns ]
ds.toDF(*new_names).show()

+------+------+----+
|gender|number|   c|
+------+------+----+
|  male|     1|null|
|female|     2|   3|
|  male|     3|   4|
+------+------+----+

##### You can also use **withColumnRenamed** to rename spark columns

In [ ]:
ds.withColumnRenamed('c', 'Quantity').show()

+------+---+--------+
|     a|  b|Quantity|
+------+---+--------+
|  male|  1|    null|
|female|  2|       3|
|  male|  3|       4|
+------+---+--------+

In [ ]:
dp.head(2)

   a  b    c
0  1  1  NaN
1  0  2  3.0

###Drop Columns

In [ ]:
dropped_col = 'c'
dp.drop( dropped_col, axis=1 ).head()

   a  b
0  1  1
1  0  2
2  1  3

In [ ]:
ds.drop(*dropped_col).show()

+------+---+
|     a|  b|
+------+---+
|  male|  1|
|female|  2|
|  male|  3|
+------+---+

## Filter

#####Read Excel
use glob to get all the csv files
in the folder

In [ ]:

import pandas as pd

In [ ]:
dp = pd.read_csv("advertising.csv")
dp.head(5)

   TV  Radio  Newspaper  Sales  Unnamed: 4
0   1  230.1       37.8   69.2        22.1
1   2   44.5       39.3   45.1        10.4
2   3   17.2       45.9   69.3         9.3
3   4  151.5       41.3   58.5        18.5
4   5  180.8       10.8   58.4        12.9

In [ ]:
ds = spark.read.csv(path = 'advertising.csv', header=True,  inferSchema=True)
ds.show(5)

+---+-----+---------+-----+----+
| TV|Radio|Newspaper|Sales| _c4|
+---+-----+---------+-----+----+
|  1|230.1|     37.8| 69.2|22.1|
|  2| 44.5|     39.3| 45.1|10.4|
|  3| 17.2|     45.9| 69.3| 9.3|
|  4|151.5|     41.3| 58.5|18.5|
|  5|180.8|     10.8| 58.4|12.9|
+---+-----+---------+-----+----+
only showing top 5 rows

In [ ]:
dp[(dp.Newspaper<20)&(dp.TV>100)].head(4)

      TV  Radio  Newspaper  Sales  Unnamed: 4
100  101  222.4        4.3   49.8        11.7
102  103  280.2       10.1   21.4        14.8
103  104  187.9       17.2   17.9        14.7
106  107   25.0       11.0   29.7         7.2

In [ ]:
ds[(ds.Newspaper<20)&(ds.TV>100)].show(4)

+---+-----+---------+-----+----+
| TV|Radio|Newspaper|Sales| _c4|
+---+-----+---------+-----+----+
|101|222.4|      4.3| 49.8|11.7|
|103|280.2|     10.1| 21.4|14.8|
|104|187.9|     17.2| 17.9|14.7|
|107| 25.0|     11.0| 29.7| 7.2|
+---+-----+---------+-----+----+
only showing top 4 rows

### With New Column
derived columns

In [ ]:
dp['tv_norm'] = dp.TV/sum(dp.TV)

In [ ]:
from pyspark.sql.functions import sum
ds.withColumn( 'tv_norm',  ds.TV/ds.select(sum(ds.TV)).collect()[0][0]).show()

+---+-----+---------+-----+----+--------------------+
| TV|Radio|Newspaper|Sales| _c4|             tv_norm|
+---+-----+---------+-----+----+--------------------+
|  1|230.1|     37.8| 69.2|22.1|4.975124378109452...|
|  2| 44.5|     39.3| 45.1|10.4|9.950248756218905E-5|
|  3| 17.2|     45.9| 69.3| 9.3|1.492537313432835...|
|  4|151.5|     41.3| 58.5|18.5|1.990049751243781E-4|
|  5|180.8|     10.8| 58.4|12.9|2.487562189054726E-4|
|  6|  8.7|     48.9| 75.0| 7.2|2.985074626865671...|
|  7| 57.5|     32.8| 23.5|11.8|3.482587064676617E-4|
|  8|120.2|     19.6| 11.6|13.2|3.980099502487562E-4|
|  9|  8.6|      2.1|  1.0| 4.8|4.477611940298507...|
| 10|199.8|      2.6| 21.2|10.6|4.975124378109452E-4|
| 11| 66.1|      5.8| 24.2| 8.6|5.472636815920398E-4|
| 12|214.7|     24.0|  4.0|17.4|5.970149253731343E-4|
| 13| 23.8|     35.1| 65.9| 9.2|6.467661691542288E-4|
| 14| 97.5|      7.6|  7.2| 9.7|6.965174129353234E-4|
| 15|204.1|     32.9| 46.0|19.0|7.462686567164179E-4|
| 16|195.4|     47.7| 52.9|22.4|7.960199004975124E-4|
| 17| 67.8|     36.6|114.0|12.5| 8.45771144278607E-4|
| 18|281.4|     39.6| 55.8|24.4|8.955223880597015E-4|
| 19| 69.2|     20.5| 18.3|11.3| 9.45273631840796E-4|
| 20|147.3|     23.9| 19.1|14.6|9.950248756218905E-4|
+---+-----+---------+-----+----+--------------------+
only showing top 20 rows

In [ ]:
ds.withColumn('tv_norm', ds.TV/ds.groupBy().agg(sum("TV")).collect()[0][0]).show()

+---+-----+---------+-----+----+--------------------+
| TV|Radio|Newspaper|Sales| _c4|             tv_norm|
+---+-----+---------+-----+----+--------------------+
|  1|230.1|     37.8| 69.2|22.1|4.975124378109452...|
|  2| 44.5|     39.3| 45.1|10.4|9.950248756218905E-5|
|  3| 17.2|     45.9| 69.3| 9.3|1.492537313432835...|
|  4|151.5|     41.3| 58.5|18.5|1.990049751243781E-4|
|  5|180.8|     10.8| 58.4|12.9|2.487562189054726E-4|
|  6|  8.7|     48.9| 75.0| 7.2|2.985074626865671...|
|  7| 57.5|     32.8| 23.5|11.8|3.482587064676617E-4|
|  8|120.2|     19.6| 11.6|13.2|3.980099502487562E-4|
|  9|  8.6|      2.1|  1.0| 4.8|4.477611940298507...|
| 10|199.8|      2.6| 21.2|10.6|4.975124378109452E-4|
| 11| 66.1|      5.8| 24.2| 8.6|5.472636815920398E-4|
| 12|214.7|     24.0|  4.0|17.4|5.970149253731343E-4|
| 13| 23.8|     35.1| 65.9| 9.2|6.467661691542288E-4|
| 14| 97.5|      7.6|  7.2| 9.7|6.965174129353234E-4|
| 15|204.1|     32.9| 46.0|19.0|7.462686567164179E-4|
| 16|195.4|     47.7| 52.9|22.4|7.960199004975124E-4|
| 17| 67.8|     36.6|114.0|12.5| 8.45771144278607E-4|
| 18|281.4|     39.6| 55.8|24.4|8.955223880597015E-4|
| 19| 69.2|     20.5| 18.3|11.3| 9.45273631840796E-4|
| 20|147.3|     23.9| 19.1|14.6|9.950248756218905E-4|
+---+-----+---------+-----+----+--------------------+
only showing top 20 rows

In [ ]:
from pyspark.sql import functions as F

In [ ]:
ds.withColumn('tv_norm', ds.TV/ds.groupBy().agg(F.sum("TV")).collect()[0][0]).show()

+---+-----+---------+-----+----+--------------------+
| TV|Radio|Newspaper|Sales| _c4|             tv_norm|
+---+-----+---------+-----+----+--------------------+
|  1|230.1|     37.8| 69.2|22.1|4.975124378109452...|
|  2| 44.5|     39.3| 45.1|10.4|9.950248756218905E-5|
|  3| 17.2|     45.9| 69.3| 9.3|1.492537313432835...|
|  4|151.5|     41.3| 58.5|18.5|1.990049751243781E-4|
|  5|180.8|     10.8| 58.4|12.9|2.487562189054726E-4|
|  6|  8.7|     48.9| 75.0| 7.2|2.985074626865671...|
|  7| 57.5|     32.8| 23.5|11.8|3.482587064676617E-4|
|  8|120.2|     19.6| 11.6|13.2|3.980099502487562E-4|
|  9|  8.6|      2.1|  1.0| 4.8|4.477611940298507...|
| 10|199.8|      2.6| 21.2|10.6|4.975124378109452E-4|
| 11| 66.1|      5.8| 24.2| 8.6|5.472636815920398E-4|
| 12|214.7|     24.0|  4.0|17.4|5.970149253731343E-4|
| 13| 23.8|     35.1| 65.9| 9.2|6.467661691542288E-4|
| 14| 97.5|      7.6|  7.2| 9.7|6.965174129353234E-4|
| 15|204.1|     32.9| 46.0|19.0|7.462686567164179E-4|
| 16|195.4|     47.7| 52.9|22.4|7.960199004975124E-4|
| 17| 67.8|     36.6|114.0|12.5| 8.45771144278607E-4|
| 18|281.4|     39.6| 55.8|24.4|8.955223880597015E-4|
| 19| 69.2|     20.5| 18.3|11.3| 9.45273631840796E-4|
| 20|147.3|     23.9| 19.1|14.6|9.950248756218905E-4|
+---+-----+---------+-----+----+--------------------+
only showing top 20 rows

In [ ]:
dp['condition'] =  dp.apply(lambda x : 1 if (( x.TV > 100 ) & (x.Radio < 30))  else 2 if x.Sales > 50 else 3, axis=1  )
dp

      TV  Radio  Newspaper  Sales  Unnamed: 4   tv_norm  condition
0      1  230.1       37.8   69.2        22.1  0.000050          2
1      2   44.5       39.3   45.1        10.4  0.000100          3
2      3   17.2       45.9   69.3         9.3  0.000149          2
3      4  151.5       41.3   58.5        18.5  0.000199          2
4      5  180.8       10.8   58.4        12.9  0.000249          2
..   ...    ...        ...    ...         ...       ...        ...
195  196   38.2        3.7   13.8         7.6  0.009751          3
196  197   94.2        4.9    8.1         9.7  0.009801          3
197  198  177.0        9.3    6.4        12.8  0.009851          3
198  199  283.6       42.0   66.2        25.5  0.009900          2
199  200  232.1        8.6    8.7        13.4  0.009950          3

[200 rows x 7 columns]

In [ ]:
ds.withColumn('condition', F.when ((ds.TV > 100) & (ds.Radio < 30 ),1).when (ds.Sales > 50, 2).otherwise(3)  ).show()

+---+-----+---------+-----+----+---------+
| TV|Radio|Newspaper|Sales| _c4|condition|
+---+-----+---------+-----+----+---------+
|  1|230.1|     37.8| 69.2|22.1|        2|
|  2| 44.5|     39.3| 45.1|10.4|        3|
|  3| 17.2|     45.9| 69.3| 9.3|        2|
|  4|151.5|     41.3| 58.5|18.5|        2|
|  5|180.8|     10.8| 58.4|12.9|        2|
|  6|  8.7|     48.9| 75.0| 7.2|        2|
|  7| 57.5|     32.8| 23.5|11.8|        3|
|  8|120.2|     19.6| 11.6|13.2|        3|
|  9|  8.6|      2.1|  1.0| 4.8|        3|
| 10|199.8|      2.6| 21.2|10.6|        3|
| 11| 66.1|      5.8| 24.2| 8.6|        3|
| 12|214.7|     24.0|  4.0|17.4|        3|
| 13| 23.8|     35.1| 65.9| 9.2|        2|
| 14| 97.5|      7.6|  7.2| 9.7|        3|
| 15|204.1|     32.9| 46.0|19.0|        3|
| 16|195.4|     47.7| 52.9|22.4|        2|
| 17| 67.8|     36.6|114.0|12.5|        2|
| 18|281.4|     39.6| 55.8|24.4|        2|
| 19| 69.2|     20.5| 18.3|11.3|        3|
| 20|147.3|     23.9| 19.1|14.6|        3|
+---+-----+---------+-----+----+---------+
only showing top 20 rows

In [ ]:
import numpy as np

In [ ]:
dp['log_tv'] = np.log(dp.TV)
dp

      TV  Radio  Newspaper  Sales  Unnamed: 4   tv_norm  condition    log_tv
0      1  230.1       37.8   69.2        22.1  0.000050          2  0.000000
1      2   44.5       39.3   45.1        10.4  0.000100          3  0.693147
2      3   17.2       45.9   69.3         9.3  0.000149          2  1.098612
3      4  151.5       41.3   58.5        18.5  0.000199          2  1.386294
4      5  180.8       10.8   58.4        12.9  0.000249          2  1.609438
..   ...    ...        ...    ...         ...       ...        ...       ...
195  196   38.2        3.7   13.8         7.6  0.009751          3  5.278115
196  197   94.2        4.9    8.1         9.7  0.009801          3  5.283204
197  198  177.0        9.3    6.4        12.8  0.009851          3  5.288267
198  199  283.6       42.0   66.2        25.5  0.009900          2  5.293305
199  200  232.1        8.6    8.7        13.4  0.009950          3  5.298317

[200 rows x 8 columns]

In [ ]:
ds.withColumn('log_tv', F.log(ds.TV)).show()

+---+-----+---------+-----+----+------------------+
| TV|Radio|Newspaper|Sales| _c4|            log_tv|
+---+-----+---------+-----+----+------------------+
|  1|230.1|     37.8| 69.2|22.1|               0.0|
|  2| 44.5|     39.3| 45.1|10.4|0.6931471805599453|
|  3| 17.2|     45.9| 69.3| 9.3|1.0986122886681096|
|  4|151.5|     41.3| 58.5|18.5|1.3862943611198906|
|  5|180.8|     10.8| 58.4|12.9|1.6094379124341003|
|  6|  8.7|     48.9| 75.0| 7.2| 1.791759469228055|
|  7| 57.5|     32.8| 23.5|11.8|1.9459101490553132|
|  8|120.2|     19.6| 11.6|13.2|2.0794415416798357|
|  9|  8.6|      2.1|  1.0| 4.8|2.1972245773362196|
| 10|199.8|      2.6| 21.2|10.6| 2.302585092994046|
| 11| 66.1|      5.8| 24.2| 8.6|2.3978952727983707|
| 12|214.7|     24.0|  4.0|17.4|2.4849066497880004|
| 13| 23.8|     35.1| 65.9| 9.2|2.5649493574615367|
| 14| 97.5|      7.6|  7.2| 9.7|2.6390573296152584|
| 15|204.1|     32.9| 46.0|19.0|  2.70805020110221|
| 16|195.4|     47.7| 52.9|22.4| 2.772588722239781|
| 17| 67.8|     36.6|114.0|12.5| 2.833213344056216|
| 18|281.4|     39.6| 55.8|24.4|2.8903717578961645|
| 19| 69.2|     20.5| 18.3|11.3|2.9444389791664403|
| 20|147.3|     23.9| 19.1|14.6| 2.995732273553991|
+---+-----+---------+-----+----+------------------+
only showing top 20 rows

##JOIN

In [ ]:
leftp = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']},
index=[0, 1, 2, 3])
rightp = pd.DataFrame({'A': ['A0', 'A1', 'A6', 'A7'],
'F': ['B4', 'B5', 'B6', 'B7'],
'G': ['C4', 'C5', 'C6', 'C7'],
'H': ['D4', 'D5', 'D6', 'D7']},
index=[4, 5, 6, 7])

In [ ]:
lefts = spark.createDataFrame(leftp)
rights = spark.createDataFrame(rightp)

#### Lef Join

In [ ]:
leftp.merge(rightp, on ="A", how="left")

    A   B   C   D    F    G    H
0  A0  B0  C0  D0   B4   C4   D4
1  A1  B1  C1  D1   B5   C5   D5
2  A2  B2  C2  D2  NaN  NaN  NaN
3  A3  B3  C3  D3  NaN  NaN  NaN

In [ ]:
lefts.join(rights, on = "a", how="left").show()

+---+---+---+---+----+----+----+
|  A|  B|  C|  D|   F|   G|   H|
+---+---+---+---+----+----+----+
| A0| B0| C0| D0|  B4|  C4|  D4|
| A1| B1| C1| D1|  B5|  C5|  D5|
| A2| B2| C2| D2|null|null|null|
| A3| B3| C3| D3|null|null|null|
+---+---+---+---+----+----+----+

#### Right Join

In [ ]:
leftp.merge(rightp, on="A", how="right")
leftp.merge(rightp, on="A", how="inner")
leftp.merge(rightp, on="A", how="outer") # full

    A    B    C    D    F    G    H
0  A0   B0   C0   D0   B4   C4   D4
1  A1   B1   C1   D1   B5   C5   D5
2  A2   B2   C2   D2  NaN  NaN  NaN
3  A3   B3   C3   D3  NaN  NaN  NaN
4  A6  NaN  NaN  NaN   B6   C6   D6
5  A7  NaN  NaN  NaN   B7   C7   D7

###  Concat Columns

In [ ]:
my_list = [('a', 2, 3),
('b', 5, 6),
('c', 8, 9),
('a', 2, 3),
('b', 5, 6),
('c', 8, 9)]
col_name = ['col1', 'col2', 'col3']

In [ ]:
dp1 = pd.DataFrame(my_list, columns = col_name)
dp1

  col1  col2  col3
0    a     2     3
1    b     5     6
2    c     8     9
3    a     2     3
4    b     5     6
5    c     8     9

In [ ]:
ds1 = spark.createDataFrame(my_list, schema = col_name)
ds1.show()

+----+----+----+
|col1|col2|col3|
+----+----+----+
|   a|   2|   3|
|   b|   5|   6|
|   c|   8|   9|
|   a|   2|   3|
|   b|   5|   6|
|   c|   8|   9|
+----+----+----+

In [ ]:
dp1['concat'] = dp1.apply(lambda x: '%s%s'%(x['col1'],x['col2']), axis=1 )
dp1

  col1  col2  col3 concat
0    a     2     3     a2
1    b     5     6     b5
2    c     8     9     c8
3    a     2     3     a2
4    b     5     6     b5
5    c     8     9     c8

In [ ]:
ds1.withColumn('concat', F.concat('col1', 'col2')).show()

+----+----+----+------+
|col1|col2|col3|concat|
+----+----+----+------+
|   a|   2|   3|    a2|
|   b|   5|   6|    b5|
|   c|   8|   9|    c8|
|   a|   2|   3|    a2|
|   b|   5|   6|    b5|
|   c|   8|   9|    c8|
+----+----+----+------+

### Group By

In [ ]:
dp1.groupby(['col1']).agg({'col2': 'mean', 'col3': 'min' } )

      col2  col3
col1
a      2.0     3
b      5.0     6
c      8.0     9

In [ ]:
ds1.groupBy(['col1']).agg({'col2': 'avg', 'col3':'avg'}).show()

+----+---------+---------+
|col1|avg(col2)|avg(col3)|
+----+---------+---------+
|   c|      8.0|      9.0|
|   b|      5.0|      6.0|
|   a|      2.0|      3.0|
+----+---------+---------+

### Window

In [ ]:
d = {'A':['a','b','c','d'],'B':['m','m','n','n'],'C':[1,2,3,6]}
dp = pd.DataFrame(d)
ds = spark.createDataFrame(dp)

In [ ]:
dp['rank'] = dp.groupby('B')['C'].rank('dense',ascending=False)
dp

   A  B  C  rank
0  a  m  1   2.0
1  b  m  2   1.0
2  c  n  3   2.0
3  d  n  6   1.0

In [ ]:
from pyspark.sql.window import Window

In [ ]:
w = Window.partitionBy('B').orderBy(ds.C.desc() )

In [ ]:
ds.withColumn('rank', F.rank().over(w) ).show()

+---+---+---+----+
|  A|  B|  C|rank|
+---+---+---+----+
|  b|  m|  2|   1|
|  a|  m|  1|   2|
|  d|  n|  6|   1|
|  c|  n|  3|   2|
+---+---+---+----+

### Rank vs Denserank

In [ ]:
d ={'Id':[1,2,3,4,5,6],
'Score': [4.00, 4.00, 3.85, 3.65, 3.65, 3.50]}
#
data = pd.DataFrame(d)
dp = data.copy()
ds = spark.createDataFrame(data)

In [ ]:
dp['dense_rank'] = dp['Score'].rank(method='dense', ascending = False)

dp['rank'] = dp["Score"].rank(method = 'min' , ascending= False) 
dp

   Id  Score  dense_rank  rank
0   1   4.00         1.0   1.0
1   2   4.00         1.0   1.0
2   3   3.85         2.0   3.0
3   4   3.65         3.0   4.0
4   5   3.65         3.0   4.0
5   6   3.50         4.0   6.0

In [ ]:
import pyspark.sql.functions as F
from pyspark.sql.window import Window

In [ ]:
w = Window.orderBy(ds.Score.desc())

In [ ]:
ds.withColumn('dense_rank', F.dense_rank().over(w) ).show()

+---+-----+----------+
| Id|Score|dense_rank|
+---+-----+----------+
|  1|  4.0|         1|
|  2|  4.0|         1|
|  3| 3.85|         2|
|  4| 3.65|         3|
|  5| 3.65|         3|
|  6|  3.5|         4|
+---+-----+----------+

In [ ]:
ds.withColumn('rank', F.rank().over(w) ).show()

+---+-----+----------+----+
| Id|Score|dense_rank|rank|
+---+-----+----------+----+
|  1|  4.0|         1|   1|
|  2|  4.0|         1|   1|
|  3| 3.85|         2|   3|
|  4| 3.65|         3|   4|
|  5| 3.65|         3|   4|
|  6|  3.5|         4|   6|
+---+-----+----------+----+

In [125]:
!git config --global user.email "mutwirifranco@gmail.com"
!git config --global user.name "MutwiriFrank"

In [122]:
!git init
!git add .
!git commit -m "first_commit"

Reinitialized existing Git repository in /content/drive/MyDrive/colabNotebooks/.git/
On branch master
nothing to commit, working tree clean
git: 'pushorigin' is not a git command. See 'git --help'.

In [128]:
!git remote set-url origin https://MutwiriFrank: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@github.com/MutwiriFrank/PysparkTutorial.git

In [130]:
!git push --set-upstream origin master

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 4.87 KiB | 711.00 KiB/s, done.
Total 5 (delta 0), reused 0 (delta 0)
To https://github.com/MutwiriFrank/PysparkTutorial.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.